defaults:
  - default.yaml

_target_: planktonzilla.dataset_import.dataset_importer.GlobalUVP5NetDatasetImporter
hf_dataset_name: globaluvp5net
push_to_hub: true

human_readable_name: A global consistent database of plankton and detritus from in situ imaging by the Underwater Vision Profiler 5
license: cc-by-4.0
description: |
  Plankton and detritus are essential components of the Earths oceans influencing biogeochemical 
  cycles and carbon sequestration. Climate change impacts their composition and marine ecosystems as 
  a whole. To improve our understanding of these changes, standardized observation methods and integrated 
  global datasets are needed to enhance the accuracy of ecological and climate models. Here, we present a 
  global dataset for plankton and detritus obtained by two versions of the Underwater Vision Profiler 5 (UVP5). 
  This release contains the images classified in 33 homogenized categories, as well as the metadata associated 
  with them, reaching 3,114 profiles and ca. 8 million objects acquired between 2008-2018 at global scale. 
  The geographical distribution of the dataset is unbalanced, with the Equatorial region (30° S - 30° N) being 
  the most represented, followed by the high latitudes in the northern hemisphere and lastly the high latitudes 
  in the Southern Hemisphere. Detritus is the most abundant category in terms of concentration (90%) and 
  biovolume (95%), although its classification in different morphotypes is still not well established. Copepoda 
  was the most abundant taxa within the plankton, with Trichodesmium colonies being the second most abundant. 
  The two versions of UVP5 (SD and HD) have different imagers, resulting in a different effective size range to 
  analyse plankton and detritus from the images (HD objects >600 µm, SD objects >1 mm) and morphological 
  properties (grey levels, etc.) presenting similar patterns, although the ranges may differ. A large number of 
  images of plankton and detritus will be collected in the future by the UVP5, and the public availability of this 
  dataset will help it being utilized as a training set for machine learning and being improved by the scientific 
  community. This will reduce uncertainty by classifying previously unclassified objects and expand the 
  classification categories, ultimately enhancing biodiversity quantification.

download_uris: https://www.seanoe.org/data/00964/107583/data/121258.zip
source_url: https://www.seanoe.org/data/00964/107583/
paperswithcode_id: "globaluvp5net"
citation_apa: |
  Nocera Ariadna, Stemmann Lars, Babin Marcel, Biard Tristan, Coustenoble Julie, Carlotti François, Coppola Laurent, 
  Courchet Lucas, Drago Laetitia, Elineau Amanda, Guidi Lionel, Hauss Helena, Jalabert Laëtitia, Karp-Boss Lee, 
  Kiko Rainer, Laget Marion, Lombard Fabien, McDonnell Andrew, Merland Camille, Motreuil Solène, Panaïotis Thelma, 
  Picheral Marc, Rogge Andreas, Waite Anya, Irisson Jean-Olivier (2025). A global consistent database of plankton 
  and detritus from in situ imaging by the Underwater Vision Profiler 5. SEANOE. https://doi.org/10.17882/107583

citation_bibtex: |
  @article{essd-2025-522,
    author = {Nocera, A. C. and Stemmann, L. and Babin, M. and Biard, T. and Coustenoble, J. and Carlotti, F. and Coppola, L. and Courchet, L. and Drago, L. and Elineau, A. and Guidi, L. and Hauss, H. and Jalabert, L. and Karp-Boss, L. and Kiko, R. and Laget, M. and Lombard, F. and McDonnell, A. and Merland, C. and Motreuil, S. and Pana\"{\i}otis, T. and Picheral, M. and Rogge, A. and Waite, A. and Irisson, J.-O.},
    doi = {10.5194/essd-2025-522},
    journal = {Earth System Science Data Discussions},
    pages = {1--37},
    title = {A global consistent database of plankton and detritus from in situ imaging by the Underwater Vision Profiler 5},
    url = {https://essd.copernicus.org/preprints/essd-2025-522/},
    volume = {2025},
    year = {2025}
  }
